services:
  - type: web
    name: ai-background-remover-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: $PORT
    autoDeploy: true

  - type: web
    name: ai-background-remover-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: PORT
        value: 3000
    autoDeploy: true
